
title: API Documentation
author: 
  name: Leon S

description: Documentation for the API

header_pages:
  - requests.md
  - responses.md
  - errors.md

remote_theme: jekyll/minima
minima:
  skin: dark
